title: "[Compilers]<Title>"
labels: ["compiler"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Have you check these sections of the docs?
        - [Compiler zksolc](https://era.zksync.io/docs/api/compiler-toolchain/solidity.html)
        - [Compiler zkvyper](https://era.zksync.io/docs/api/compiler-toolchain/vyper.html)
        - [Configure hardhat-zksolc](https://era.zksync.io/docs/api/hardhat/hardhat-zksync-solc.html)
        - [Configure hardhat-zkvyper](https://era.zksync.io/docs/api/hardhat/hardhat-zksync-vyper.html)
  - type: checkboxes
    attributes:
      label: Which compiler are you using?
      options:
        - label: zksolc
        - label: zkvyper
  - type: input
    id: version
    attributes:
      label: Which version of Solidity or Vyper?
      description: The Solidity or Vyper version from your config file
    validations:
      required: true
  - type: input
    id: zkversion
    attributes:
      label: zksolc/zkvyper version?
      description: The zksolc/zkvyper version from your config file
    validations:
      required: false
  - type: textarea
    id: issue
    attributes:
      label: Explain the issue
      value: |
        ...
      render: bash
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Link to your repo?
      description: Link to the repo with the contracts and config file
    validations:
      required: false
